name: Perl

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        perl: [ '5.10', '5.34' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
#     - run: cpanm --installdeps .
      - run: perl -V
      - run: prove -lv t
      - run: echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
      - run: find ${GITHUB_WORKSPACE} -name '*.pl' -o -name '*.pm'
      - run: find . -name '*.pl' -o -name '*.pm'
      - run: find ${GITHUB_WORKSPACE} -name '*.pl' -print -exec perl -c {} \;
