name: Perl

on:
  push:
    paths:
      - 'perl/**.pl'
      - 'perl/**.pm'
      - '.github/workflows/perl.yml'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        perl: [ '5.10', '5.34' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
#     - run: cpanm --installdeps .
      - run: perl -V
      - run: prove -lv perl/t
      - run: echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
      - run: find perl -name '*.pl' -print0 | xargs -0 -n1 perl -c
      - run: find perl -name '*.pm' -print0 | xargs -0 -n1 perl -c
# podchecker returns 0 for success, 1 for error, 2 for missing POD or no input file
      - run: find perl -name '*.pm' -print0 | xargs -0 -n1 podchecker
