name: Ruby

on:
  push:
    paths:
      - 'ruby/**.rb'
      - '.github/workflows/ruby.yml'

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        working-directory: ./ruby
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby: [2.3, 2.5, 2.6, 2.7, 3.0]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: ${{ matrix.ruby }}
#     - run: bundle install
#     - run: bundle exec rake
      - run: find . -name '*.rb' -print0 | xargs -0 -n1 ruby -wc
