name: Shell
on:
  push:
    paths:
      - 'shell/**.sh'
      - '.github/workflows/shell.yml'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        working-directory: ./shell
    strategy:
      matrix:
        os: [ubuntu, macos]
    steps:
      - uses: actions/checkout@master
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
