name: Shell
on:
  push:
    paths:
      - 'shell/**.sh'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
